<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Weee\Block\Item\Price\Renderer */

$item = $block->getItem();
?>
<?php
$product = $item->getProduct();
$regularPrice = $product->getPriceInfo()->getPrice('regular_price')->getAmount()->getValue();
$finalPrice = $product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue();
$hasSpecialPrice = $finalPrice < $regularPrice;
$hasSpecialPriceCss = ($hasSpecialPrice) ? ' has-special-price': '';
?>
<?php if ($block->displayPriceInclTax() || $block->displayBothPrices()): ?>
    <span class="price-including-tax" data-label="<?= $block->escapeHtml(__('Incl. Tax')) ?>">
        <?php if ($block->displayPriceWithWeeeDetails()): ?>
            <span class="cart-tax-total"
                data-mage-init='{"taxToggle": {"itemTaxId" : "#unit-item-tax-details<?= /* @escapeNotVerified */ $item->getId() ?>"}}'>
        <?php else: ?>
            <span class="cart-price<?php echo $hasSpecialPriceCss ?>">
        <?php endif; ?>
            <?php $itemPrice = ($hasSpecialPrice) ? $product->getPrice() : $block->getUnitDisplayPriceInclTax(); ?>
            <?php /* @escapeNotVerified */ echo $block->formatPrice($itemPrice); ?>
            </span>

        <?php if ($this->helper('Magento\Weee\Helper\Data')->getApplied($item)): ?>
            <span class="cart-tax-info" id="unit-item-tax-details<?= /* @escapeNotVerified */ $item->getId() ?>" style="display: none;">
                <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($item) as $tax): ?>
                    <span class="weee" data-label="<?= /* @escapeNotVerified */ $tax['title'] ?>">
                        <?= /* @escapeNotVerified */ $block->formatPrice($tax['amount_incl_tax'], true, true) ?>
                    </span>
                <?php endforeach; ?>
            </span>

            <?php if ($block->displayFinalPrice()): ?>
                <span class="cart-tax-total"
                    data-mage-init='{"taxToggle": {"itemTaxId" : "#unit-item-tax-details<?= /* @escapeNotVerified */ $item->getId() ?>"}}'>
                    <span class="weee" data-label="<?= $block->escapeHtml(__('Total Incl. Tax')) ?>">
                        <?= /* @escapeNotVerified */ $block->formatPrice($block->getFinalUnitDisplayPriceInclTax()) ?>
                    </span>
                </span>
            <?php endif; ?>
        <?php endif; ?>
    </span>
<?php endif; ?>

<?php if ($block->displayPriceExclTax() || $block->displayBothPrices()): ?>
    <span class="price-excluding-tax" data-label="<?= $block->escapeHtml(__('Excl. Tax')) ?>">
        <?php if ($block->displayPriceWithWeeeDetails()): ?>
            <span class="cart-tax-total"
                data-mage-init='{"taxToggle": {"itemTaxId" : "#eunit-item-tax-details<?= /* @escapeNotVerified */ $item->getId() ?>"}}'>
        <?php else: ?>
            <span class="cart-price<?php echo $hasSpecialPriceCss ?>">
        <?php endif; ?>
                <?php $itemPrice = ($hasSpecialPrice) ? $product->getPrice() : $block->getUnitDisplayPriceExclTax(); ?>
                <?php /* @escapeNotVerified */ echo $block->formatPrice($itemPrice); ?>
            </span>

        <?php if ($this->helper('Magento\Weee\Helper\Data')->getApplied($item)): ?>
            <span class="cart-tax-info" id="eunit-item-tax-details<?= /* @escapeNotVerified */ $item->getId() ?>"
                style="display: none;">
                <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($item) as $tax): ?>
                    <span class="weee" data-label="<?= /* @escapeNotVerified */ $tax['title'] ?>">
                        <?= /* @escapeNotVerified */ $block->formatPrice($tax['amount'], true, true) ?>
                    </span>
                <?php endforeach; ?>
            </span>

            <?php if ($block->displayFinalPrice()): ?>
                <span class="cart-tax-total"
                      data-mage-init='{"taxToggle": {"itemTaxId" : "#eunit-item-tax-details<?= /* @escapeNotVerified */ $item->getId() ?>"}}'>
                    <span class="weee" data-label="<?= $block->escapeHtml(__('Total')) ?>">
                        <?= /* @escapeNotVerified */ $block->formatPrice($block->getFinalUnitDisplayPriceExclTax()) ?>
                    </span>
                </span>
            <?php endif; ?>
        <?php endif; ?>
    </span>
<?php endif; ?>

<!-- special price -->
<?php if ($hasSpecialPrice): ?>
    <span class="cart special-price">
        <?php echo $block->formatPrice($finalPrice); ?>
    </span>
<?php endif; ?>
