<?php $websiteCode = $block->getWebsiteCode() ?>
<?php if (!$block->isLoggedIn() && ($websiteCode=="default" || !$websiteCode)): ?>
    <li>
        <a href="https://b2b.splosh.com.au/customer/account/login/"> <?= $block->getLabel() ?></a>
    </li>
<?php elseif(!$block->isLoggedIn() && $websiteCode=="nz_b2c_store_view"): ?>
    <li>
        <a href="https://b2b.splosh.co.nz/customer/account/login/"> <?= $block->getLabel() ?></a>
    </li>
<?php endif; ?>