<div class="messages-container">
    <h4>Please wait</h4>
    <h4>Your order is being processed</h4>
    <p>Do not refresh this page</p>
    <p>Please note: large orders may take up to 5 minutes to process... so make yourself a cup of tea and relax!</p>
</div>
<style type="text/css">
.loader {
    text-align: center;
    position: absolute;
    top: 30%;
    width: 100%;
}
.opacity-bg {
    top: 0;
    height: 100%;
    width: 100%;
    background: rgba(255, 255, 255, 0.9);
}
.loading-mask .loader > img {
    position: static;
    height: 50px;
    width: 50px;
}
.messages-container {
    position: relative;
    vertical-align: middle;
    text-align: center;
    width: 100%;
}
</style>
